### ISSUE TITLE
TODO: Allgemein

### ISSUE THREAD

**Issue by claasdeboer** [fsr/python-beginner-lessons#1]
- [ ] Variablenzuweisung
- [ ] Standartoperationen (+,-,*,/) Typungebunden (1. Woche nur INT)
- [ ] Python Interpreter/Shell (online, offline) 
- [ ] Hinweise on "How to install Python"
- [ ] Erste Aufgaben (1. Woche)
- [ ] Chad Python vs. ...
